### ISSUE TITLE
"await"-issue with python3.6

### ISSUE THREAD

**Issue by mirko** [seidler2547/home-assistant-cc#2]
I'm getting the following error with python3.6

```
Mar 10 17:21:02 owrt hass[4532]: #033[32m2018-03-10 17:21:02 INFO (MainThread) [homeassistant.components.climate] Setting up climate.sygonix#033[0m

Mar 10 17:21:02 owrt hass[4532]: #033[31m2018-03-10 17:21:02 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved#033[0m

Mar 10 17:21:02 owrt hass[4532]: Traceback (most recent call last):

Mar 10 17:21:02 owrt hass[4532]:   File "/tasks.py", line 180, in _step

Mar 10 17:21:02 owrt hass[4532]:   File "/space/stick/venv/ha/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 258, in _async_add_entity

Mar 10 17:21:02 owrt hass[4532]:     await entity.async_added_to_hass()

Mar 10 17:21:02 owrt hass[4532]: TypeError: object generator can't be used in 'await' expression#033[0m

Mar 10 17:21:02 owrt hass[4532]: #033[32m2018-03-10 17:21:02 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1520702462.3392568, level=ERROR, message=Error doing job: Task exception was never retrieved, exception=Traceback (most recent call last):

Mar 10 17:21:02 owrt hass[4532]:   File "/tasks.py", line 180, in _step

Mar 10 17:21:02 owrt hass[4532]:   File "/space/stick/venv/ha/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 258, in _async_add_entity

Mar 10 17:21:02 owrt hass[4532]:     await entity.async_added_to_hass()

Mar 10 17:21:02 owrt hass[4532]: TypeError: object generator can't be used in 'await' expression

Mar 10 17:21:02 owrt hass[4532]: , source=helpers/entity_platform.py>
```

**Comment by seidler2547** [comment]
I updated the code, can you `git pull` and try the fix?

**Comment by mirko** [comment]
> I updated the code, can you git pull and try the fix?

Ha! Awesome! Btw., I dropped you an email (email address according to your git commits) as I'm considering to replace the bluepy component and would appreciate having talked to your before starting.

EDIT: it works btw. ;) - well, the HA-component does at least, so the fix works. I "just" fail with the actual connection to my devices via bluepy now..

**Comment by mirko** [comment]
There's a pretty decent library out there for the sygonix[1] which I now wrapped with a home-assistent component[2].

As I already I mentioned, I did so because the bluepy dependency is what I'm not the biggest fan of, as well the mqtt-bridge, which drained quite some resources on my embedded system and - although I got it working - the characteristics gathered and provided via mqtt were off in some way, so the HA-component didn't know what to do with those.

Please don't get me wrong here: I'm really glad about your efforts and this implementation. I just wanted to explain, why I went another path.

[1]https://github.com/xrucka/cometblue
[2]https://github.com/mirko/home-assistant/blob/cometblue/homeassistant/components/climate/cometblue.py
